basePath: /api/v1
definitions:
  dto.RegisterRequest:
    properties:
      email:
        type: string
      name:
        maxLength: 30
        minLength: 3
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - name
    - password
    type: object
  dto.RegisterResponse:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  handlers.HealthHandler:
    description: Health check response
    properties:
      status:
        example: ok
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: champuplove@gmail.com
    name: API Support
  description: A RESTful API server with user authentication and MongoDB integration
  termsOfService: https://mywebideal.work
  title: Example Go Project API
  version: "1.0"
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: Post the API's register
      parameters:
      - description: User registration details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RegisterResponse'
      summary: Register endpoint
      tags:
      - auth
  /health:
    get:
      consumes:
      - application/json
      description: Get the API's health status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.HealthHandler'
      summary: Health check endpoint
      tags:
      - health
schemes:
- http
- https
securityDefinitions:
  Bearer:
    description: 'Enter the token with the `Bearer: ` prefix, e.g. "Bearer abcde12345".'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
